apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: devops
spec:
  containers:
  - name: nginx
    image: httpd:latest
    ports:
    - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: my-nginix-service
spec:
  type: LoadBalancer
  selector:
    app: devops
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
